#!/bin/bash

apt install nasm mtools -y
nasm -f bin -o boot.bin boot.asm
rm floppy.img
mkdosfs -C floppy.img 1440
dd conv=notrunc if=boot.bin of=floppy.img
nasm -f bin -o mykernel.bin mykernel.asm
mcopy -i floppy.img mykernel.bin ::/

for entry in "programs"/*
do
  echo "Output File Name (for $entry) --> "
  read output
  nasm -f bin -o "$output" "$entry"
  mcopy -i floppy.img "$output" ::/
done

/usr/bin/printf "Build succesful!\n"
