#!/bin/bash
rm -r out
mkdir out
apt install nasm mtools -y
cp rosasm/rosasm-std.inc .
nasm -f bin -o out/boot.bin boot/boot.asm
mkdosfs -C out/floppy.img 1440
dd conv=notrunc if=out/boot.bin of=out/floppy.img
nasm -f bin -o out/mykernel.bin kernel/mykernel.asm
mcopy -i out/floppy.img out/mykernel.bin ::/

for entry in "programs"/*
do
  echo "Output File Name (for $entry) --> "
  read output
  nasm -f bin -o out/"$output" "$entry"
  mcopy -i out/floppy.img out/"$output" ::/
done

mkdir out/floppy_disk_image
mv out/floppy.img out/floppy_disk_image/

rm rosasm-std.inc

/usr/bin/printf "Build succesful!\n"
